name: PR-check
run-name: ${{ github.actor }} Pull Request pysh-check
on: [push]

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true
  
jobs:
  run-pysh-check:
    runs-on: client
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get install black pycodestyle pydocstyle shellcheck python3
      - run: black --version

      - run: git clone https://github.com/PelionIoT/scripts-internal
      # Lets not run pysh-check on itself (it already has PR job for it)
      - run: echo . >scripts-internal/.nopyshcheck
      - run: scripts-internal/pysh-check/pysh-check.sh --workdir .
      - name: Cleanup .gitconfig
        run: rm -f ~/.gitconfig

  install-on-ubuntu-22-04:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install e2e-python-test-library
        run: |
          pip install wheel
          python3 setup.py bdist_wheel
          cd dist/
          pip install -I client_test_lib*.whl
      - name: Cleanup .gitconfig
        run: rm -f ~/.gitconfig
  
  install-on-ubuntu-20-04:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Install e2e-python-test-library
        run: |
          pip install wheel
          python3 setup.py bdist_wheel
          cd dist/
          pip install -I client_test_lib*.whl
      - name: Cleanup .gitconfig
        run: rm -f ~/.gitconfig

  call-mcce-linux:
    # Note - primary/master version of this test is in the mcce-repo.
    uses: ./.github/workflows/MCCE-Test-Linux.yml
    with:
      tested_branch: ${{ github.GITHUB_REF }}
    secrets: inherit
